services:
  postgres:
    container_name: ms_pg_slq
    image: postgres
    environment:
      POSTGRES_USER: timur
      POSTGRES_PASSWORD: timur
      POSTGRES_DB: keycloak
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - aircraft-net
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mail_hog_am
    ports:
      - 1025:1025
      - 8025:8025

  keycloak:
    container_name: keycloak-am
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9098:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: timur
      KC_DB_PASSWORD: timur
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    volumes:
      - ./src/main/resources/keycloak/import:/opt/keycloak/data/import
      - ./src/main/resources/keycloak/themes:/opt/keycloak/themes/mytheme
    command:
     -v start-dev --import-realm
    depends_on:
     - postgres
    networks:
     - aircraft-net

networks:
  aircraft-net:
    driver: bridge

volumes:
  postgres:

  #  app:
  #    build: .
  #    restart: always
  #    ports:
  #      - 8080:8080
  #    depends_on:
  #      - db
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/aircraft_maintenance_db
  #      - SPRING_DATASOURCE_USERNAME=timur
  #      - SPRING_DATASOURCE_PASSWORD=timur